# Generated by Django 3.1.5 on 2021-01-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailpassword',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_mail', to='users.user'),
            preserve_default=False,
        ),
    ]
